repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.0
    hooks:
      # Run the linter. Disable for now.
      #- id: ruff-chec
      # Run the formatter.
      - id: ruff-format
        # To not format patches!
        exclude: ^patches/
