#!/usr/bin/env bash

# Seed 42

echo "Seed 42"

python dfaas_train.py --algorithm PPO --model configs/models/softplus.json \
    --iterations 300 --runners 5 --seed 42 --env-config configs/env/five_agents.json 42 &

python dfaas_train.py --algorithm APL \
    --iterations 300 --runners 5 --seed 42 --env-config configs/env/five_agents.json 42 &

python dfaas_train.py --algorithm SAC --model configs/models/softplus.json \
    --iterations 300 --runners 5 --seed 42 --env-config configs/env/five_agents.json 42 &

wait
 
python dfaas_upperbound.py --iterations 300 --runners 5 --seed 42 --env-config configs/env/five_agents.json 42 &

python dfaas_upperbound.py --iterations 300 --runners 5 --seed 43 --env-config configs/env/five_agents.json 43 &

wait

# Seed 43

echo "Seed 43"

python dfaas_train.py --algorithm PPO --model configs/models/softplus.json \
    --iterations 300 --runners 5 --seed 43 --env-config configs/env/five_agents.json 43 &

python dfaas_train.py --algorithm APL \
    --iterations 300 --runners 5 --seed 43 --env-config configs/env/five_agents.json 43 &

python dfaas_train.py --algorithm SAC \
    --iterations 300 --runners 5 --seed 43 --env-config configs/env/five_agents.json 43 &

wait


# Seed 44

echo "Seed 44"

python dfaas_train.py --algorithm PPO --model configs/models/softplus.json \
    --iterations 300 --runners 5 --seed 44 --env-config configs/env/five_agents.json 44 &

python dfaas_train.py --algorithm APL \
    --iterations 300 --runners 5 --seed 44 --env-config configs/env/five_agents.json 44 &

python dfaas_train.py --algorithm SAC \
    --iterations 300 --runners 5 --seed 44 --env-config configs/env/five_agents.json 44 &

python dfaas_upperbound.py --iterations 300 --runners 5 --seed 44 --env-config configs/env/five_agents.json 44 &

wait

# Seed 45

echo "Seed 45"

python dfaas_train.py --algorithm PPO --model configs/models/softplus.json \
    --iterations 300 --runners 5 --seed 45 --env-config configs/env/five_agents.json 45 &

python dfaas_train.py --algorithm APL \
    --iterations 300 --runners 5 --seed 45 --env-config configs/env/five_agents.json 45 &

wait

python dfaas_train.py --algorithm SAC \
    --iterations 300 --runners 5 --seed 45 --env-config configs/env/five_agents.json 45 &

python dfaas_upperbound.py --iterations 300 --runners 5 --seed 45 --env-config configs/env/five_agents.json 45 &

wait

# Seed 46

echo "Seed 46"

python dfaas_train.py --algorithm PPO --model configs/models/softplus.json \
    --iterations 300 --runners 5 --seed 46 --env-config configs/env/five_agents.json 46 &

python dfaas_train.py --algorithm APL \
    --iterations 300 --runners 5 --seed 46 --env-config configs/env/five_agents.json 46 &

wait

python dfaas_train.py --algorithm SAC \
    --iterations 300 --runners 5 --seed 46 --env-config configs/env/five_agents.json 46 &

python dfaas_upperbound.py --iterations 300 --runners 5 --seed 46 --env-config configs/env/five_agents.json 46 &

wait

# Seed 47

echo "Seed 47"

python dfaas_train.py --algorithm PPO --model configs/models/softplus.json \
    --iterations 300 --runners 5 --seed 47 --env-config configs/env/five_agents.json 47 &

python dfaas_train.py --algorithm APL \
    --iterations 300 --runners 5 --seed 47 --env-config configs/env/five_agents.json 47 &

python dfaas_train.py --algorithm SAC --model configs/models/softplus.json \
    --iterations 300 --runners 5 --seed 47 --env-config configs/env/five_agents.json 47 &

wait
 
python dfaas_upperbound.py --iterations 300 --runners 5 --seed 47 --env-config configs/env/five_agents.json 47 &

python dfaas_train.py --algorithm SAC --model configs/models/softplus.json \
    --iterations 300 --runners 5 --seed 46 --env-config configs/env/five_agents.json 46 &

# Seed 48

echo "Seed 48"

python dfaas_train.py --algorithm PPO --model configs/models/softplus.json \
    --iterations 300 --runners 5 --seed 48 --env-config configs/env/five_agents.json 48 &


python dfaas_train.py --algorithm SAC \
    --iterations 300 --runners 5 --seed 48 --env-config configs/env/five_agents.json 48 &

wait

python dfaas_train.py --algorithm APL \
    --iterations 300 --runners 5 --seed 48 --env-config configs/env/five_agents.json 48 &

python dfaas_upperbound.py --iterations 300 --runners 5 --seed 48 --env-config configs/env/five_agents.json 48 &

wait

echo "Done"
