#!/usr/bin/env bash
#
# This is a small utility script to run common used commands in the project. See
# the show_help function for more information.

set -euo pipefail
trap 'echo "Error occurred at line $LINENO"; exit 1' ERR

# Default notebooks directory.
NOTEBOOK_DIR="${NOTEBOOK_DIR:-notebooks}"

run() {
    echo "$@"
    "$@"
}

show_help() {
    cat << EOF
Usage: $0 <command> [options]

Commands:
  notebook-export [notebook1.ipynb notebook2.ipynb ...]
      Convert Jupyter notebooks to HTML using nbconvert. If no notebook is
      specified, converts all notebooks in the "${NOTEBOOK_DIR}" directory.

  notebook-export-clean
      Remove HTML files generated by notebook-export from the "${NOTEBOOK_DIR}"
      directory.

  notebook-server-start
      Start Jupyter Notebook server with "jupyter_notebook_config.py" config.

  notebook-lint
      Run nbstripout and black on all notebooks in the "${NOTEBOOK_DIR}"
      directory.

  help
      Show this help message.

Make sure that jupyter, black and nbstripout are installed.
EOF
}

notebook_export() {
    local files
    if [[ $# -eq 0 ]]; then
        files=$NOTEBOOK_DIR/*.ipynb
    else
        files=$@
    fi

    run jupyter nbconvert --no-input --to html $files
}

notebook_export_clean() {
    run rm --verbose "$NOTEBOOK_DIR"/*.html
}

notebook_server_start() {
    run jupyter notebook --config jupyter_notebook_config.py
}

notebook_lint() {
    run nbstripout "$NOTEBOOK_DIR"/*.ipynb
    run black "$NOTEBOOK_DIR"/*.ipynb
}

# Default command is help, if not given.
cmd="${1:-help}"

case "$cmd" in
    notebook-export)
        # Move to the next CLI argument.
        shift || true
        notebook_export "$@"
        ;;
    notebook-export-clean)
        notebook_export_clean "$@"
        ;;
    notebook-server-start)
        notebook_server_start
        ;;
    notebook-lint)
        notebook_lint
        ;;
    help|*)
        show_help
        ;;
esac
