disable_gpu = false
iterations = 2000
algorithm.name = "PPO"
algorithm.gamma = 0.7
algorithm.lambda = 0.3
training_num_episodes = 1
runners = 1
model = "configs/models/softplus.json"
seed = 42
checkpoint_interval = 0
evaluation_interval = 25
evaluation_num_episodes = 20
