disable_gpu = false
iterations = 10000
algorithm = "PPO"
training_num_episodes = 6
runners = 3
model = "configs/models/softplus.json"
seed = 42
checkpoint_interval = 500
evaluation_interval = 500
evaluation_num_episodes = 10

[[policies]]
name = "policy_node_0"
class = "APLPolicy"

[[policies]]
name = "policy_node_1"
# Use default policy (PPO) (class = None).
