disable_gpu = false
iterations = 20000
algorithm = "PPO"
runners = 1
model = "configs/models/softplus.json"
seed = 42
checkpoint_interval = 1000
evaluation_interval = 1000

[[policies]]
name = "policy_node_0"
class = "APLPolicy"

[[policies]]
name = "policy_node_1"
# Use default policy (PPO) (class = None).
