disable_gpu = false
iterations = 10000
algorithm.name = "SAC"
algorithm.gamma = 0.7
training_num_episodes = 1
runners = 1
model = "configs/models/softplus.json"
seed = 42
checkpoint_interval = 500
evaluation_interval = 50
evaluation_num_episodes = 10

[[policies]]
name = "policy_node_0"
class = "APLPolicy"

[[policies]]
name = "policy_node_1"
# Use default policy (SAC) (class = None).
