#             ┌────────┐              
#             │        │              
#        ┌────┼ Node 0 ├────┐         
#        │    │        │    │         
#        │    └────────┘    │         
#        │                  │         
#        │                  │         
#   ┌────┴───┐         ┌────┴───┐     
#   │        │         │        │     
#   │ Node 1 ├─────────┤ Node 2 │     
#   │        │         │        │     
#   └────────┘         └────────┘     
#                                     
#network = ["node_0 node_1 node_2", "node_1 node_2"]

#              ┌────────┐             
#              │        │             
#         ┌────┼ Node 0 ├────┐        
#         │    │        │    │        
#         │    └────────┘    │        
#         │                  │        
#         │                  │        
#    ┌────┴───┐         ┌────┴───┐    
#    │        │         │        │    
#    │ Node 1 │         │ Node 2 │    
#    │        │         │        │    
#    └────────┘         └────────┘    
# 
network = ["node_0 node_1 node_2", "node_1 node_0", "node_2 node_0"]

input_rate_same_method = true
input_rate_method = "synthetic-sinusoidal"
